### ISSUE TITLE
OscScreenGrabLAN.py line 21 may need updating to from PIL import Image

### ISSUE THREAD

**Issue by thephantom1492** [RoGeorge/DS1054Z_screen_capture#1]
Traceback (most recent call last):
  File "OscScreenGrabLAN.py", line 21, in <module>
    import Imaging
ImportError: No module named Imaging

replacing it with: from PIL import Image
seems to work, but still give errors later on
This is on gentoo with python 2.7

**Comment by jwr** [comment]
I have just installed this on Ubuntu 16 (xenial) and to get it to work I had to make this one-line change (to "from PIL import Image"). After the change everything works fine.

Thanks for the great piece of software!

**Comment by RoGeorge** [comment]
Could not reproduce with Python 2.7.9
Reproducible with Python 2.7.12.
Updated the script and installation instructions in order to use pillow.

Thank you very much for your feedback.
